#!/bin/bash

PROMPT_LINES=2

input_buffer=""

init_terminal() {
    # Hide cursor to avoid flickering
    tput civis

    # Scroll enough for the prompt in case we're at the
    # bottom of the screen
    for i in $(seq 1 $PROMPT_LINES); do
        echo
    done

    # Move cursor to the top of the room we just made
    tput cuu $PROMPT_LINES

    # Save cursor position
    tput sc

    # Exclude prompt from scrollable area
    tput csr 0 "$(($(tput lines) - PROMPT_LINES - 1))"

    # Changing scrollable area moves cursor, so put it back
    tput rc
}

restore_terminal() {
    clear_prompt

    tput csr 0 "$(tput lines)"
    tput rc
    tput cnorm
}

eval_javascript_in_gnome_shell() {
    json=$(mktemp)
    busctl call --user --json=short               \
                org.gnome.Shell                   \
                /org/gnome/Shell                  \
                org.gnome.Shell                   \
                Eval "s" "$1" > "$json"
    result=$(jq '.data[0]' < "$json")
    output=$(jq '.data[1] | select(. != null and . != "") | try fromjson catch .' < "$json")
    rm -f "$json"

    if [ "$result" = "false" ]; then
        echo -e "\e[31m${output:1:-1}\e[0m" > /dev/stderr
        return 1
    fi

    echo "$output"
    return 0
}

eval_javascript_in_looking_glass() {
    # encode the text so we can side-step complicated escaping rules
    ENCODED_TEXT=$(echo -n "$1" | xxd -p -c 9999999)

    eval_javascript_in_gnome_shell "
        const GLib = imports.gi.GLib;
        Main.createLookingGlass();
        const results = Main.lookingGlass._resultsArea;
        Main.lookingGlass._entry.text = '${ENCODED_TEXT}'.replace(/([0-9a-fA-F]{2})/g, (_, h) => String.fromCharCode(parseInt(h, 16)));
        Main.lookingGlass._entry.clutter_text.activate();
        GLib.timeout_add(GLib.PRIORITY_DEFAULT, 125, () => {
            const index = results.get_n_children() - 1;
            if (index < 0)
                return;
            const resultsActor = results.get_children()[index];
            const output = \`\${resultsActor.get_children()[1].get_children()[0].text}\${resultsActor.get_children()[1].get_children()[1].get_children()[0].text}\`;
            Main.lookingGlass._lastEncodedResult = output.split('').map(char => char.charCodeAt(0).toString(16).padStart(2, '0')).join('');
        });
    " > /dev/null

    if [ $? -ne 0 ]; then
        return
    fi

    sleep .250

    OUTPUT=$(eval_javascript_in_gnome_shell 'Main.lookingGlass._lastEncodedResult;' | xxd -r -p)

    if [ -z "$OUTPUT" ]; then
        echo -e "\e[31mCould not fetch result from call\e[0m" > /dev/stderr
        return
    fi

    eval_javascript_in_gnome_shell "delete Main.lookingGlass._lastEncodedResult;" > /dev/null

    echo ">>> $1"
    echo "${OUTPUT}"
}

jump_to_prompt() {
    # Move to the bottom of the terminal
    tput cup $(($(tput lines) - PROMPT_LINES)) 0
}

clear_prompt() {
    jump_to_prompt
    tput el
}

ask_user_for_input() {
    # Save cursor position
    tput sc

    clear_prompt

    tput cnorm
    read -p ">>> " -re input_buffer
    STATUS="$?"
    tput civis

    [ $STATUS != 0 ] && exit

    if [ "$input_buffer" = "quit" -o "$input_buffer" = "q" -o "$input_buffer" = "exit" ]; then
        exit
    fi

    # Save input to history
    history -s "$input_buffer"

    # Move cursor back to saved position before output
    tput rc
}

quit_message() {
    # Move to just below the prompt
    tput cup $(($(tput lines) - PROMPT_LINES + 1)) 0

    echo -ne "Type quit to exit"
    ask_user_for_input
}

load_history() {
    while IFS= read -r line; do
        history -s "$line"
    done < <(eval_javascript_in_gnome_shell 'Main.lookingGlass._history._history.join("\n");' | jq -r '. | select(. != null and . != "") | try fromjson catch .')
}

check_for_unsafe_mode() {
    unsafe_mode=$(eval_javascript_in_gnome_shell 'global.context.unsafe_mode')

    if [ "$unsafe_mode" != "true" ]; then
        echo -e "Please enable unsafe-mode in the Flags tab of looking glass." > /dev/stderr
        exit
    fi
}

main_loop() {
    while true; do
        ask_user_for_input
        eval_javascript_in_looking_glass "$input_buffer"
    done
}

check_for_unsafe_mode

trap 'quit_message' SIGINT
trap restore_terminal EXIT

init_terminal
load_history
main_loop
restore_terminal
